# Python Task – Workforce Insights Dashboard

## Employee Skill Analysis

This notebook performs employee skill and workforce analytics using Python.

### Objectives

- Load and analyze employee data
- Check missing values
- Analyze employees by department
- Analyze skill distribution
- Identify employees requiring skill development
- Identify top-performing employees
- Generate workforce insights and KPIs

In [1]:
import pandas as pd

print("Pandas imported successfully!")

Pandas imported successfully!

In [2]:
import pandas as pd

df = pd.read_csv("../data/employees.csv")

df.head()

,employee_id,employee_name,department,job_role,primary_skill,skill_level,experience_years,performance_score,training_hours,engagement_score
0,EMP001,Aarav Sharma,IT,Software Engineer,Python,Advanced,5,92,40,88
1,EMP002,Priya Reddy,IT,Data Analyst,SQL,Advanced,4,88,35,90
2,EMP003,Rahul Kumar,HR,HR Executive,Recruitment,Intermediate,3,82,20,85
3,EMP004,Sneha Patel,Finance,Financial Analyst,Excel,Advanced,6,90,30,87
4,EMP005,Vikram Singh,IT,Data Engineer,Python,Advanced,7,95,45,92

In [3]:
import pandas as pd
import numpy as np
import plotly.express as px

In [4]:
print("Dataset Shape:", df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nDataset Information:")
df.info()

Dataset Shape: (15, 10)

Column Names:
['employee_id', 'employee_name', 'department', 'job_role', 'primary_skill', 'skill_level', 'experience_years', 'performance_score', 'training_hours', 'engagement_score']

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   employee_id        15 non-null     str
 1   employee_name      15 non-null     str
 2   department         15 non-null     str
 3   job_role           15 non-null     str
 4   primary_skill      15 non-null     str
 5   skill_level        15 non-null     str
 6   experience_years   15 non-null     int64
 7   performance_score  15 non-null     int64
 8   training_hours     15 non-null     int64
 9   engagement_score   15 non-null     int64
dtypes: int64(4), str(6)
memory usage: 1.3 KB

In [5]:
print("Missing Values:")

df.isnull().sum()

Missing Values:

employee_id          0
employee_name        0
department           0
job_role             0
primary_skill        0
skill_level          0
experience_years     0
performance_score    0
training_hours       0
engagement_score     0
dtype: int64

In [6]:
duplicate_count = df.duplicated().sum()

print("Number of Duplicate Records:", duplicate_count)

Number of Duplicate Records: 0

In [7]:
df.describe()

       experience_years  performance_score  training_hours  engagement_score
count         15.000000          15.000000       15.000000         15.000000
mean           4.400000          86.133333       34.666667         85.600000
std            1.882248           6.728051       10.082989          6.127223
min            1.000000          72.000000       20.000000         70.000000
25%            3.000000          81.500000       27.500000         83.000000
50%            4.000000          88.000000       35.000000         87.000000
75%            5.500000          91.500000       42.500000         90.000000
max            8.000000          95.000000       50.000000         93.000000

In [8]:
department_count = df["department"].value_counts()

print("Employees by Department:")
print(department_count)

Employees by Department:
department
IT            7
HR            3
Finance       2
Marketing     2
Operations    1
Name: count, dtype: int64

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

In [2]:
df = pd.read_csv("../data/employees.csv")
df.head()

,employee_id,employee_name,department,job_role,primary_skill,skill_level,experience_years,performance_score,training_hours,engagement_score
0,EMP001,Aarav Sharma,IT,Software Engineer,Python,Advanced,5,92,40,88
1,EMP002,Priya Reddy,IT,Data Analyst,SQL,Advanced,4,88,35,90
2,EMP003,Rahul Kumar,HR,HR Executive,Recruitment,Intermediate,3,82,20,85
3,EMP004,Sneha Patel,Finance,Financial Analyst,Excel,Advanced,6,90,30,87
4,EMP005,Vikram Singh,IT,Data Engineer,Python,Advanced,7,95,45,92

In [3]:
department_count = df["department"].value_counts()

print(department_count)

department
IT            7
HR            3
Finance       2
Marketing     2
Operations    1
Name: count, dtype: int64

In [4]:
fig = px.bar(
    x=department_count.index,
    y=department_count.values,
    title="Employee Distribution by Department",
    labels={
        "x": "Department",
        "y": "Number of Employees"
    }
)

fig.show()

In [5]:
skill_count = df["primary_skill"].value_counts()

print("Skill Distribution:")
print(skill_count)

Skill Distribution:
primary_skill
Python         3
Excel          3
SQL            2
Power BI       2
Recruitment    1
Java           1
Training       1
SEO            1
AWS            1
Name: count, dtype: int64

In [6]:
fig = px.bar(
    x=skill_count.index,
    y=skill_count.values,
    title="Employee Skill Distribution",
    labels={
        "x": "Primary Skill",
        "y": "Number of Employees"
    }
)

fig.show()

In [7]:
skill_development = df[df["skill_level"] == "Beginner"]

print("Employees Requiring Skill Development:")
display(skill_development)

Employees Requiring Skill Development:

,employee_id,employee_name,department,job_role,primary_skill,skill_level,experience_years,performance_score,training_hours,engagement_score
6,EMP007,Kiran Kumar,IT,Junior Developer,Java,Beginner,1,72,50,70

In [8]:
top_performers = df.sort_values(
    by="performance_score",
    ascending=False
).head(5)

print("Top Performing Employees:")
display(top_performers)

Top Performing Employees:

,employee_id,employee_name,department,job_role,primary_skill,skill_level,experience_years,performance_score,training_hours,engagement_score
4,EMP005,Vikram Singh,IT,Data Engineer,Python,Advanced,7,95,45,92
9,EMP010,Divya Iyer,IT,Data Scientist,Python,Advanced,6,94,50,93
14,EMP015,Aditya Joshi,IT,Cloud Engineer,AWS,Advanced,5,93,45,90
0,EMP001,Aarav Sharma,IT,Software Engineer,Python,Advanced,5,92,40,88
12,EMP013,Sanjay Das,Operations,Operations Analyst,Excel,Advanced,8,91,25,86

In [9]:
avg_performance = df.groupby("department")["performance_score"].mean()

print("Average Performance Score by Department:")
print(avg_performance)

Average Performance Score by Department:
department
Finance       87.000000
HR            84.666667
IT            87.428571
Marketing     80.500000
Operations    91.000000
Name: performance_score, dtype: float64

In [10]:
fig = px.bar(
    x=avg_performance.index,
    y=avg_performance.values,
    title="Average Performance Score by Department",
    labels={
        "x": "Department",
        "y": "Average Performance Score"
    }
)

fig.show()

In [11]:
total_employees = len(df)

total_departments = df["department"].nunique()

average_performance = df["performance_score"].mean()

employees_needing_development = len(
    df[df["skill_level"] == "Beginner"]
)

print("========== WORKFORCE INSIGHTS ==========")
print(f"Total Employees: {total_employees}")
print(f"Total Departments: {total_departments}")
print(f"Average Performance Score: {average_performance:.2f}")
print(f"Employees Needing Skill Development: {employees_needing_development}")
print("========================================")

========== WORKFORCE INSIGHTS ==========
Total Employees: 15
Total Departments: 5
Average Performance Score: 86.13
Employees Needing Skill Development: 1
========================================